### PR TITLE
refactor: N-06 Incomplete Encapsulation

### LINKED ISSUE #568: audit: N-06 Incomplete Encapsulation
For efficiency reasons, the StarknetSpaceManager uses uint256 values to internally
represent booleans. However, the uint256 is also returned from external queries, which
requires the caller to know the convention.
In the interest of predictability, consider returning a boolean when queried externally.

### PR DESCRIPTION
**Pull request by pscott**
Closes #568

### CODE REVIEW

**Comment by Orland0x** [comment]
do you think this is worth it considering it will then deviate from sx-evm? I assume the sx.js clients will use a lot of the same code for the solidity contracts in sx-sn and sx-evm particularly

**Comment by pscott** [comment]
Brings the question: should we also update this on SX-EVM side maybe?

**Comment by Orland0x** [comment]
> Brings the question: should we also update this on SX-EVM side maybe?

Dont think its really worth it post audit, feels like a minor/debatable thing. 

Its the responsibility of external integrators to check the interfaces of the contracts they interact with. its not like we are implementing some existing standard.

**Comment by pscott** [comment]
Ok then happy to close this PR and add a comment for the auditors

**Pull request closed without merging**
