### PR TITLE
add IQuorum

### LINKED ISSUE #523: expose quorum

### PR DESCRIPTION
**Pull request by pscott**
Not sure if the `IQuorum` interface should be in the folder `interfaces` or if it should be elsewhere. Thoughts @Orland0x ?

Closes #523

### CODE REVIEW

**Comment by Orland0x** [comment]
Should we expose both quorum and proposal status in a single interface for `SimpleQuorum`?

**Comment by pscott** [comment]
Yeah I don't know if it should be in the same interface. I think we should merge this one and discuss about it in https://github.com/snapshot-labs/sx-starknet/pull/527

**Comment by Orland0x** [comment]
> Yeah I don't know if it should be in the same interface. I think we should merge this one and discuss about it in #527

okay

**Review by Orland0x — APPROVED** [review]
uTACK

**Pull request merged**
