### PR TITLE
Update to scarb 2.6.4

### LINKED ISSUE #613: update versions
update scarb version, cairo version, and dependencies

### PR DESCRIPTION
**Pull request by pscott**
- Updates to scarb 2.6.4
- Use openzeppelin's components
- Update CI
- Use rust-based starknet-devnet

This PR also disables the L1 <-> L2 tests. This is done while waiting for Shardlabs to come up with a js wrapper to interact with the devnet and anvil.

Closes #613

### CODE REVIEW

**Review by ChaituVR — APPROVED** [review]
utAck on request of @pscott

**Comment by pscott** [comment]
thank you @ChaituVR senpai

**Comment by ivpavici** [comment]
hello! regarding

> This PR also disables the L1 <-> L2 tests. This is done while waiting for Shardlabs to come up with a js wrapper to interact with the devnet and anvil.

You can give a try, feedback for now is quite good:
https://github.com/0xSpaceShard/starknet-devnet-js

**Comment by pscott** [comment]
@ivpavici thanks ! We had not seen the update was already here. We will be integrating this very soon :D

**Pull request merged**
