### PR TITLE
Make sure all uint256 are valid

### LINKED ISSUE #369: add `uint256_check()` for every uint256
It should not be possible to pass an invalid `Uint256` to the contracts or store an invalid one in the contact state

### PR DESCRIPTION
**Pull request by pscott**
Closes #369

### CODE REVIEW

**Review by Orland0x — APPROVED** [review]
LGTM

**Comment by Orland0x** [comment]
We could combine `FeltUtils` and `Uint256Utils` into a single lib called `MathUtils` or something?

**Comment by pscott** [comment]
Good idea!

**Comment by Orland0x** [comment]
> Good idea!


Cool, Ill do it on the formatting PR

**Pull request merged**
